apiVersion : apps/v1
kind: Deployment
metadata:
  name: "devops1-2caf"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "devops1-2caf"
  template:
    metadata:
      labels:
        app: "devops1-2caf"
    spec:
      containers:
        - name: "devops1-2caf"
          image: "devops015.azurecr.io/devops1"
          ports:
          - containerPort: 80