apiVersion: v1
kind: Service
metadata:
    name: "devops1-2caf"
    labels:
        app: "devops1-2caf"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "devops1-2caf"